enableGlobalCache: true

nodeLinker: node-modules

packageExtensions:
  "@auth/neo4j-adapter@*":
    peerDependencies:
      "@auth/core": "*"
  next@*:
    peerDependencies:
      "@babel/core": "*"
      "@opentelemetry/api": "*"

yarnPath: .yarn/releases/yarn-4.6.0.cjs
